const fs = require('fs');
const root = require('path').join(__dirname, '..', 'assets') + '/';
global.window = global; window.ETO_BUNDLE = true;
(0, eval)(fs.readFileSync(root + 'common.js', 'utf8'));
const cfgs = {}; ETO.page = c => (cfgs[c.file || c.title] = c);
for (const f of fs.readdirSync(root + 'pages')) { window.ETO_FILE = f; (0, eval)(fs.readFileSync(root + 'pages/' + f, 'utf8')); }
const byTitle = {}; Object.values(cfgs).forEach(c => (byTitle[c.title] = c));
const calc = (page, id) => byTitle[page].calcs.find(c => c.id === id);
const def = c => { const v = {}; c.inputs.forEach(i => (v[i.k] = i.t === 'table' ? JSON.parse(JSON.stringify(i.v)) : i.v)); return v; };
const optval = (c,k,x) => c.inputs.find(i=>i.k===k).opts.find(o=>String(o[0])===String(x))[0]; // engine behaviour: original option value
const get = (r, label) => r.results.find(x => x.l === label).v;
let fail = 0;
const eq = (name, got, exp, tol = 1e-3) => { const ok = Math.abs(got - exp) <= tol * Math.max(1, Math.abs(exp)); if (!ok) fail++; console.log((ok ? 'PASS ' : 'FAIL ') + name + '  got=' + got + ' expected=' + exp); };

const T = (page, id, over, label, exp, tol) => { const c = calc(page, id); const v = def(c); for (const k in over) v[k] = (c.inputs.find(i => i.k === k) || {}).opts ? optval(c, k, over[k]) : over[k]; eq(page.split(' ')[0] + '#' + id + ' ' + label, get(c.run(v), label), exp, tol || 1e-3); };
const C = 'Cable Calculations', PW = 'Electrical Power Calculations';
// engine toggle bug (select option types preserved)
let c = calc(C, 'vd'); let v = def(c); const a0 = get(c.run(v), 'Voltage drop');
v.sys = optval(c, 'sys', '1'); v.sys = optval(c, 'sys', '3'); eq('vd toggle 3->1->3 unchanged', get(c.run(v), 'Voltage drop'), a0);
T(C, 'vd', {}, 'Voltage drop', 13.553, 2e-3);                                   // IEC 60228 R, 50 mm2 Cu @70C
T(C, 'vd', { sys: 'dc', v: 24, i: 30, l: 20, s: 10, t: 40, n: 1 }, 'Voltage drop', 2.4722, 2e-3);
T(C, 'size', { mode: 'p', p: 20, v: 230, pf: 0.8, eff: 100, sys: '1' }, 'Design current', 108.696);
T(C, 'sc', { isc: 25, t: 0.3, k: 143 }, 'Minimum size', 95.756);
T('Electrical Power Calculations', 'i3', {}, 'Line current', 90.2335);
T('Power Factor Calculations', 'pfc', {}, 'Capacitor bank', 221.293);
T('Power Factor Calculations', 'ww', {}, 'Power factor', 0.85425);
T('Motor Calculations', 'flc', { p: 90, pf: 0.87, e: 94 }, 'Full-load current', 144.405);
T('Motor Calculations', 'slip', { nr: 1770 }, 'Slip', 1.6667);
T('Motor Calculations', 'torque', { p: 90, n: 1775 }, 'Rated torque', 484.225);
T('Generator Calculations', 'mstart', {}, 'Voltage dip', 20.0927);
T('Generator Calculations', 'droop', {}, 'Frequency at load', 60.72);
T('Transformer Calculations', 'sc', {}, 'Prospective Isc', 13.1216);
T('Transformer Calculations', 'cur', {}, 'Secondary current', 98.4216 * 1, 1e-3);
T('Battery & UPS Calculations', 'auto', {}, 'Realistic autonomy', 5.4803);
T('Earthing & Insulation', 'ir', {}, 'IR corrected to 40 °C', 42.5 * 1);
T('Earthing & Insulation', 'pi', {}, 'Polarisation Index', 2.6923);
T('Harmonics / THD', 'res', {}, 'Resonance order', 10.5409);
T('VFD / Drive Calculations', 'dc', {}, 'Nominal DC bus', 594);
T('VFD / Drive Calculations', 'brk', {}, 'Max resistor value', 6.14545);
T('VFD / Drive Calculations', 'aff', {}, 'Power', 38.4);
T('Crane Electrical Calculations', 'hoist', { m: 50, v: 20, em: 80 }, 'Shaft power', 204.375);
T('Crane Electrical Calculations', 'hyd', {}, 'Hydraulic power', 70.4583);
T('Crane Electrical Calculations', 'hyd', {}, 'Pump shaft power', 82.4074);
T('Thruster Calculations', 'delta', { p: 1500, x1: 40, x2: 80 }, 'Additional load ΔP', 729.167);
T('Jacking System Calculations', 'mech', { w: 8000, v: 0.6, em: 70, n: 24 }, 'Total shaft power', 1121.143);
T('Lighting Calculations', 'fix', {}, 'Fixtures (calculated)', 3.63636);
T('Short-circuit & Protection', 'isc', { L: 0, mf: 0 }, 'At source terminals', 32.804);
console.log(fail ? ('FAILURES: ' + fail) : 'ALL PASS');

// ---------------- Level 4 benchmarks (independent values) ----------------
const UM = 'Unit Converter – Mechanical & General', UE = 'Unit Converter – Electrical & Marine', M = 'Mathematics', GE = 'Geometry & Tanks', CI = 'Circuit Theory Formulas', MT = 'Mechanical, Fluid & Thermal';
const conv2 = (page, id, over, unitLabelIncludes, exp, tol) => { const c = calc(page, id); const v = def(c); for (const k in over) v[k] = over[k]; const r = c.run(v); const t = r.results.find(x => x.l.includes(unitLabelIncludes) || (x.u && x.u.includes(unitLabelIncludes))); if (!t) { fail++; console.log('FAIL missing ' + unitLabelIncludes); return; } eq(page.slice(0, 12) + '#' + id + ' → ' + unitLabelIncludes, t.v, exp, tol || 1e-4); };
conv2(UM, 'press', { x: 1, from: 'bar', to: 'psi' }, 'psi', 14.5037738);
conv2(UM, 'power', { x: 100, from: 'kw', to: 'hp' }, 'HP', 134.102209);
conv2(UM, 'speed', { x: 10, from: 'kn', to: 'kmh' }, 'km/h', 18.52);
conv2(UM, 'temp', { x: 25, from: 'c', to: 'f' }, '°F', 77);
conv2(UM, 'temp', { x: 0, from: 'k', to: 'c' }, '°C', -273.15);
conv2(UM, 'energy', { x: 1, from: 'kwh', to: 'mj' }, 'MJ', 3.6);
conv2(UM, 'vol', { x: 1, from: 'gal', to: 'l' }, 'litre', 3.785411784);
conv2(UM, 'len', { x: 1, from: 'nm', to: 'm' }, 'metre', 1852);
conv2(UM, 'dens', { x: 0.85, from: 'sg', to: 'api' }, 'API', 34.9706, 1e-3);
conv2(UM, 'dens', { x: 35, from: 'api', to: 'sg' }, 'Specific gravity', 0.8498, 1e-3);
conv2(UM, 'torque', { x: 100, from: 'nm', to: 'lbft' }, 'lbf·ft', 73.7562, 1e-4);
conv2(UE, 'prefix', { x: 4700, from: 'n', to: 'u' }, 'micro', 4.7);
conv2(UE, 'kcmil', { x: 500, from: 'kcmil', to: 'mm2' }, 'mm²', 253.35);
T2 = (page, id, over, label, exp, tol) => { const c = calc(page, id); const v = def(c); for (const k in over) v[k] = over[k]; eq(page.slice(0, 12) + '#' + id + ' ' + label, get(c.run(v), label), exp, tol || 1e-3); };
T2(UE, 'awg', { n: 4 }, 'Diameter', 5.1894, 1e-3);
T2(UE, 'awg', { n: -3 }, 'AWG 4/0 area', 107.22, 1e-3);
T2(UE, 'mm2awg', { a: 21.15 }, 'Exact AWG', 4.0, 5e-3);
T2(UE, 'wave', { w: 'sine', x: 440, q: 'rms' }, 'Peak', 622.25, 1e-3);
T2(UE, 'db', { m: 'vr', x: 2 }, 'Result', 6.0206, 1e-4);
T2(UE, 'batt', { g: 'ah', x: 200, v: 24 }, 'Energy', 4800 / 1, 1e-6);
T2(UE, 'sdt', { s: 'd', v: 5, t: 24 }, 'Distance', 120, 1e-6);
T2(M, 'pct', { m: 'chg', x: 80, y: 100 }, 'Result', 25);
T2(M, 'quad', { a: 1, b: -3, c: 2 }, 'x₁', 2);
T2(M, 'lin2', {}, 'x', 3.2);
T2(M, 'lin3', {}, 'x', 2); T2(M, 'lin3', {}, 'y', 3); T2(M, 'lin3', {}, 'z', -1);
T2(M, 'rtri', { m: 'ab', a: 3, b: 4 }, 'c (hypotenuse)', 5);
T2(M, 'rtri', { m: 'ab', a: 3, b: 4 }, 'Angle A', 36.8699, 1e-4);
T2(M, 'tri3', { m: 'sss', a: 3, b: 4, c: 5 }, 'Area', 6);
T2(M, 'tri3', { m: 'sss', a: 3, b: 4, c: 5 }, 'Angle C', 90, 1e-6);
T2(M, 'trig', { x: 30, u: 'deg' }, 'sin', 0.5);
T2(M, 'phasor', {}, 'Resultant magnitude', 0, 1e-6);
T2(M, 'stat', {}, 'Mean', 12.0833, 1e-4);
T2(M, 'comb', { n: 10, r: 3 }, 'nCr (unordered)', 120);
T2(M, 'base', { s: 'FF', b: 16 }, 'Bits needed', 8);
T2(M, 'series', { t: 'ap', a: 2, d: 3, n: 10 }, 'Sₙ', 155);
T2(M, 'gcd', { a: 48, b: 180 }, 'GCD', 12);
T2(GE, 'hcyl', { m: 'v', dia: 2.4, len: 6, h: 0.9 }, 'Liquid volume', 9.2972, 1e-3);
T2(GE, 'hcyl', { m: 'v', dia: 2.4, len: 6, h: 1.2 }, 'Fill', 50, 1e-4);
T2(GE, 'hcyl', { m: 'h', dia: 2.4, len: 6, p: 25 }, 'Liquid height', 0.715233, 1e-5);
T2(GE, 'area', { s: 'circle', r: 5 }, 'Area', 78.5398, 1e-4);
T2(GE, 'vol', { s: 'sph', r: 1 }, 'Volume', 4.18879, 1e-4);
T2(GE, 'seg', { r: 10, by: 'ang', x: 60 }, 'Chord length', 10, 1e-6);
T2(GE, 'pipe', { od: 114.3, t: 6.02, l: 6 }, 'Steel weight per metre', 16.07, 5e-3);
T2(CI, 'ohm', {}, 'Resistance', 23);
T2(CI, 'rc', {}, 'Charge level at t', 63.2121, 1e-4);
T2(CI, 'rlc', {}, 'Impedance Z', 18.3199, 2e-3);
T2(CI, 'rlc', {}, 'Resonant frequency f₀', 71.176, 1e-3);
T2(CI, 'ds', { m: 'dy', x: 30, y: 30, z: 30 }, 'R_A', 10);
T2(CI, 'lp', { c: 'y', vl: 440, il: 100 }, 'Phase voltage', 254.034, 1e-4);
T2(CI, 'pubase', {}, 'Impedance on new base', 48);
T2(CI, 'stored', {}, 'Capacitor energy', 2.7, 1e-6);
T2(MT, 'pts', { s: 'p', t: 484, n: 1775 }, 'Power', 89.97, 5e-3);
T2(MT, 'belt', {}, 'Belt length', 2554.98, 1e-4);
T2(MT, 'shaft', {}, 'Shear stress', 28.294, 1e-3);
T2(MT, 'sling', { w: 2000, n: 2, a: 45, sf: 1 }, 'Tension per leg', 13.8697, 1e-3);
T2(MT, 'pump', {}, 'Hydraulic power', 33.5109, 1e-3);
T2(MT, 'pipe', { q: 100, id: 100 }, 'Velocity', 3.5368, 1e-3);
T2(MT, 'heat', {}, 'Energy required', 83720, 1e-6);
T2(MT, 'fuel', {}, 'Thermal efficiency', 42.1546, 1e-3);
T2(MT, 'vent', {}, 'Air flow', 5.7679, 1e-3);
console.log(fail ? ('FAILURES: ' + fail) : 'ALL PASS (incl. Level 4)');

// ---------------- Levels 5–7 & additions ----------------
const TT = (page, id, over, label, exp, tol) => { const c = calc(page, id); const v = def(c); for (const k in over) v[k] = over[k]; const r = c.run(v); const x = r.results.find(q => q.l === label); if (!x) { fail++; console.log('FAIL missing ' + page + '#' + id + ' ' + label); return; } if (typeof exp === 'string') { const ok = String(x.v) === exp; if (!ok) fail++; console.log((ok ? 'PASS ' : 'FAIL ') + id + ' ' + label + ' got=' + x.v + ' exp=' + exp); return; } eq(page.slice(0, 14) + '#' + id + ' ' + label, x.v, exp, tol || 1e-3); };
const VD = (page, id, over, s) => { const c = calc(page, id); const v = def(c); for (const k in over) v[k] = over[k]; const r = c.run(v); const ok = r.verdict && r.verdict.s === s; if (!ok) fail++; console.log((ok ? 'PASS ' : 'FAIL ') + id + ' verdict ' + (r.verdict && r.verdict.s) + ' exp ' + s); };
TT('Testing & Commissioning', 'wres', {}, 'Imbalance', 1.21065, 1e-4);
TT('Testing & Commissioning', 'earthel', {}, 'Electrode resistance', 4.8);
TT('Testing & Commissioning', 'loop', {}, 'PEFC', 0.547619, 1e-5);
TT('Testing & Commissioning', 'ttr', {}, 'Expected ratio', 1.568182, 1e-6);
TT('Testing & Commissioning', 'symc', { ma: 254, aa: 0, mb: 254, ab: -120, mc: 254, ac: 120 }, 'Positive sequence', 254, 1e-9);
TT('Testing & Commissioning', 'symc', { ma: 254, aa: 0, mb: 254, ab: -120, mc: 254, ac: 120 }, 'Unbalance factor V2/V1', 0, 1e-9);
TT('Signals & Loops', 'ma', { m: 'ma', x: 12, lrv: 0, urv: 10 }, 'Process value', 5);
TT('Signals & Loops', 'plc', { pre: 's7', m: 'r2e', x: 13824, lrv: 0, urv: 16 }, 'Process value', 8);
TT('Signals & Loops', 'pulse', {}, 'Flow', 2.5, 1e-9);
TT('Temperature Sensors', 'pt', { r0: 100, m: 'r', x: 119.4 }, 'Temperature', 50.007466, 1e-6);
TT('Temperature Sensors', 'pt', { r0: 100, m: 't', x: -100 }, 'Resistance', 60.2558, 1e-5);
TT('Temperature Sensors', 'tc', { ty: 'K', m: 'e', x: 20.644, tc: 0 }, 'Hot-junction temperature', 500, 2e-4);
TT('Temperature Sensors', 'tc', { ty: 'J', m: 't', x: 760, tc: 0 }, 'emf at 0 °C reference', 42.919, 1e-4);
TT('Process Measurement', 'dpflow', {}, 'Flow', 60, 1e-9);
TT('Process Measurement', 'level', {}, 'LRV (4 mA)', 50.2591, 1e-4);
TT('Process Measurement', 'level', {}, 'URV (20 mA)', 653.368, 1e-4);
TT('Calibration & Loop Check', 'cal5', {}, 'As-found max error', 0.875, 1e-6);
TT('PMS / DP / Blackout Simulator', 'trip', {}, 'Outcome', 'SURVIVES');
TT('PMS / DP / Blackout Simulator', 'trip', {}, 'Final loading', 53.125, 1e-6);
TT('PMS / DP / Blackout Simulator', 'trip', { load: 2300 }, 'Outcome', 'BLACKOUT');
TT('PMS / DP / Blackout Simulator', 'reserve', {}, 'Loading after largest DG lost', 90.625, 1e-6);
TT('PMS / DP / Blackout Simulator', 'dp', {}, 'Bus A lost → available on B', 2700);
TT('PMS / DP / Blackout Simulator', 'rocof', {}, 'Initial ROCOF', 6);
TT('Battery & UPS Calculations', 'h2', {}, 'Required air flow', 0.96, 1e-9);
TT('Communications & Networks', 'subnet', {}, 'Network', '192.168.10.0/24');
TT('Communications & Networks', 'subnet', { ip: '10.4.17.200', p: 20 }, 'Broadcast', '10.4.31.255');
TT('Communications & Networks', 'nmea', {}, 'Checksums valid', '4 / 4');
TT('Communications & Networks', 'serial', { b: 9600, d: 8, p: 1, s: 1 }, 'Character time', 1.145833, 1e-5);
TT('Communications & Networks', 'poe', {}, 'Worst-case PSE demand', 273.2, 1e-9);
TT('Short-circuit & Protection', 'idmt', { c: 'si', is: 1000, tms: 0.2, i: 6000 }, 'Operating time', 0.7674385, 1e-6);
TT('Short-circuit & Protection', 'ct', {}, 'Actual burden', 15.0584, 1e-4);
TT('Short-circuit & Protection', 'coord', {}, 'Downstream trip time at fault', 0.03, 1e-9);
TT('Earthing & Insulation', 'ngr', {}, 'System charging current I_C', 0.90116, 1e-4);
TT('Earthing & Insulation', 'ngr', {}, 'Resistance', 79.674, 1e-4);
TT('Transformer Calculations', 'inrush', {}, 'Inrush peak', 4016.3497, 1e-6);
TT('Generator Calculations', 'multi', {}, 'Total starting kVA', 1322.59, 1e-4);
console.log(fail ? ('FAILURES: ' + fail) : 'ALL PASS (incl. Levels 5–7)');

// ---------------- 3rd-party audit regression checks ----------------
{
  const run = (p, id, o) => { const c = calc(p, id), v = Object.assign(def(c), o); return c.run(v); };
  const ok = (name, cond) => { if (!cond) fail++; console.log((cond ? 'PASS ' : 'FAIL ') + name); };
  ok('std() never rounds down past list end', ETO.std(ETO.STD_SIZES, 700) === null && ETO.std(ETO.STD_SIZES, 630) === 630);
  ok('breaker above 5000 A is not "selected"', run('Short-circuit & Protection', 'sel', { ib: 6000, iz: 7000 }).verdict.s === 'warn');
  ok('cable s/c > 630 mm² flagged', String(run('Cable Calculations', 'sc', { isc: 120, t: 1 }).results[1].v).startsWith('>'));
  eq('IEC 60228 Al 10 mm² @20 °C', ETO.res('Al', 10, 20) * 1000, 3.08, 1e-9);
  eq('IEC 60228 Cu 1.0 mm² @20 °C', ETO.res('Cu', 1, 20) * 1000, 18.1, 1e-9);
  eq('IEC 60228 Cu 2.5 mm² @70 °C', ETO.res('Cu', 2.5, 70) * 1000, 7.98 * (1 + 0.00393 * 50), 1e-9);
  ok('PF correction never negative', run('Power Factor Calculations', 'pfc', { pf1: 0.95, pf2: 0.9 }).results[0].v === 0);
  ok('IEEE 519: Isc/IL = 20 → 20<50 row (8 %), 19.99 → 5 %', run('Harmonics / THD', 'thdi', { ratio: 20 }).results.find(x => x.l.includes('TDD')).v === 8 && run('Harmonics / THD', 'thdi', { ratio: 19.99 }).results.find(x => x.l.includes('TDD')).v === 5);
  ok('shunt sized on full-scale voltage (0–10 V → 500 Ω, never > 10 V)', run('Signals & Loops', 'shunt', { v0: 0, v1: 10 }).results[0].v === 500);
  console.log(fail ? ('FAILURES: ' + fail) : 'ALL PASS (incl. audit regression)');
}
